Load sidecards and narratives
nextstrain/auspice.us pull request #23
Opened 2022-03-07 04:57 UTC by jameshadfield

See commit messages for details. I’ll post a tarball of files used for testing this on slack. 

The measurements sidecar failed to load, which seemed on the surface to be an auspice error (not auspice.us). We can make this a separate issue perhaps?

Closes #7

2022-03-07 22:05 UTC, joverlee521 requested changes
Glad to see this wasn't _too_ big of change! 

I left some minor inline comments and I also have some general comments:

- I noticed that all "valid" files are read into memory even though we only support displaying "one thing". This can lead to a long wait for the files to be read or memory issues if someone drags on a crazy number of files. We might want to delay reading the files to right before the dispatch of the data so we only read the files that will actually be used. 

- A reminder to update the "Currently supported data formats" section on the splash page.  It would be helpful to also include a comment on which dropped files should be expected to be displayed. For example, a narrative will always take precedence over the datasets and if multiple datasets are added then only two will be displayed as two trees side by side.

2022-03-07 22:21 UTC, jameshadfield commented on auspice_client_customisation/handleDroppedFiles.js
> +  }
Yup - I wanted to first load the main dataset files (i.e. `Dataset()`s) then add in sidecars to those.

2022-03-08 04:18 UTC, jameshadfield commented on auspice_client_customisation/handleDroppedFiles.js
> +          logs.push(`Read ${file.name} as a sidecar file of ${datasets[mainNameLower].name}`);
Yes, if we were to to change it to `await readFile(file);`. As it stands,`datasets[mainNameLower][sidecarPropName]` is a promise that will resolve/reject. The promises are used in the [loadSidecars function](https://github.com/nextstrain/auspice/blob/master/src/actions/loadData.js#L305-L331), and most of them have a `catch` handler to deal with a rejected promise.

2022-03-08 04:33 UTC, jameshadfield commented on auspice_client_customisation/handleDroppedFiles.js
> +    if (filesSeen.has(file.name) || !nameLower.endsWith("json")) continue;
Sure should be! Fixed

2022-03-08 05:42 UTC, jameshadfield commented
Thanks @joverlee521!

> I noticed that all "valid" files are read into memory even though we only support displaying "one thing". This can lead to a long wait for the files to be read or memory issues if someone drags on a crazy number of files. 

This might be possible, but in practice I think it'll be rarely encountered. As you point out, there are tricks we can use if we need to address this situation in the future (unless you've experienced this in testing?). For what it's worth, I think dropping multiple datasets onto auspice.us isn't very useful, except in the case of narratives. 

>  A reminder to update the "Currently supported data formats" section on the splash page. 

Thanks for the reminder! Done in [86a1a34](https://github.com/nextstrain/auspice.us/pull/23/commits/86a1a34049722fe32b7b05ec624cb85c8e4d2e38)

2022-03-08 18:18 UTC, joverlee521 commented on auspice_client_customisation/handleDroppedFiles.js
> +          logs.push(`Read ${file.name} as a sidecar file of ${datasets[mainNameLower].name}`);
Ah right, totally missed these get used in the loadSidecars functions. That makes sense!

2022-03-08 18:28 UTC, joverlee521 commented
> This might be possible, but in practice I think it'll be rarely encountered. As you point out, there are tricks we can use if we need to address this situation in the future (unless you've experienced this in testing?).

Yeah, I don't see people doing this but just wanted to point it out. When I was testing, I dropped all files from the auspice `get-data` command just to see what would happen. It took a little longer to load but nothing crashed.

2022-03-10 02:07 UTC, merged